version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - ./config.env  
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./config.env  
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: